name: JFrog OIDC Docker PoC

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JFrog CLI via OIDC
        id: jfrog
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: http://54.67.82.130:8082
        with:
          oidc-provider-name: github-actions-oidc
          oidc-audience: jfrog   # 

      - name: Verify JFrog authentication
        run: jfrog rt ping

      - name: Docker login to JFrog
        run: |
          echo "${{ steps.jfrog.outputs.oidc-token }}" | \
          docker login 54.67.82.130:8082 \
            --username "${{ steps.jfrog.outputs.oidc-user }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t 54.67.82.130:8082/platform-docker-virtual/nginx:poc-${{ github.run_number }} \
            .

      - name: Push Docker image
        run: |
          docker push \
            54.67.82.130:8082/platform-docker-virtual/nginx:poc-${{ github.run_number }}
